twig:
    file_name_pattern: '*.twig'
    globals:
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    form_themes:
        ['security/captcha.html.twig']

when@test:
    twig:
        strict_variables: true
        
